"""Update models

Revision ID: 05c66172341f
Revises: 90b7a6251127
Create Date: 2025-09-21 10:03:35.283140

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '05c66172341f'
down_revision = '90b7a6251127'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('borrowing_slip', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('SPENDING', 'APPROVED', 'REJECTED', collation='utf8mb4_unicode_ci'),
               type_=sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='status'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('borrowing_slip', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='status'),
               type_=mysql.ENUM('SPENDING', 'APPROVED', 'REJECTED', collation='utf8mb4_unicode_ci'),
               existing_nullable=False)

    # ### end Alembic commands ###
