"""Update models

Revision ID: 90b7a6251127
Revises: 9e58b3f4d561
Create Date: 2025-09-21 10:02:03.793142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90b7a6251127'
down_revision = '9e58b3f4d561'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('borrowing_slip', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('status', sa.Enum('SPENDING', 'APPROVED', 'REJECTED', name='status'), nullable=False))

    # ### end Alembic commands ###
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('borrowing_slip', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
